services:

  db:
    image: cassandra:5.0
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./data:/var/lib/cassandra
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 8G

  ai:
    image: ollama/ollama:0.6.2
    container_name: ollama
    ports:
      - "11434:11434"
    restart: on-failure
    deploy:
      resources:
        limits:
          memory: 2G

  app:
    build: .
    container_name: digestwave
    ports:
      - "8080:8080"
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - db
      - ai
    profiles:
      - app
    restart: on-failure
