services:

  db:
    image: cassandra:5.0
    container_name: cassandra
    ports:
      - "9042:9042"

  ai:
    image: ollama/ollama:0.6.2
    container_name: ollama
    ports:
      - "11434:11434"
